# Dockerfile
FROM public.ecr.aws/lambda/nodejs:18

COPY rag/package*.json ./
#COPY shared/package*.json ./

# Install production dependencies
#RUN npm ci --only=production --ignore-scripts && \
    #npm cache clean --force

RUN mpm install    

# Copy shared code
COPY shared ./shared

# Copy the rest of the application
COPY rag/. .

CMD ["apiHandler.handler"]
