apiVersion: apps/v1
kind: Deployment
metadata:
  name: canvas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canvas
  template:
    metadata:
      labels:
        app: canvas
    spec:
      containers:
        - name: canvas
          image: 881490088456.dkr.ecr.us-east-1.amazonaws.com/canvas-service:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: font-volume
              mountPath: /usr/share/fonts/truetype/custom/
              readOnly: true
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: "250m" # Minimum CPU request
              memory: "256Mi" # Minimum memory request
            limits:
              cpu: "500m" # Maximum CPU limit
              memory: "512Mi" # Maximum memory limit
      volumes:
        - name: font-volume
          configMap:
            name: font-config
      # Optional if you need to refresh font cache (for Linux fonts system)
      initContainers:
        - name: init-font-cache
          image: busybox
          command:
            [
              "sh",
              "-c",
              "mkdir -p /usr/share/fonts/truetype/custom/ && sleep 5",
            ]

---
apiVersion: v1
kind: Service
metadata:
  name: canvas-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true" #use Internal NLB
spec:
  selector:
    app: canvas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: canvas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canvas
  minReplicas: 1
  maxReplicas: 100 # Can scale up to 1000 pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # Target 60% CPU usage
